### PR TITLE
Login and Logout templates

### PR DESCRIPTION
**Pull request by squareZ**
see contao-bootstrap/templates/#5

### CODE REVIEW

**Comment by dmolineus** [comment]
Thanks for contributing! There a some things I'd like to have improved before merging:

- [ ] Please remove the left over `<br>` tag at the end. It makes strange margins
- [ ] It would be great if you could provide an template for the logout module as well, so both is covered.
- [ ] As I use phpcq/phpcq as build system, It would be great that you at yourself as author to the modified autoload.php (squareZ <squareZ@users.noreply.github.com>). It you want to use another name or email, you also have to add yourself to the `.check-author,yml` as described [here](https://github.com/phpcq/author-validation#configuration).

You see an green check icon if everything is okay afther the build script checked the pull request (where you see first the yellow circle and now the red cross).

**Comment by dmolineus** [comment]
If you want to make it perfect and go the "extra mile", using the 2cl template for an horizontal form would be great (that's how I do for the default form templates of Contao which actually use tables). I use some config vars, where the default `col-` classes are defined for the forms.

Instead of hardcode the columns you can use `<?php echo Netzmacht\Bootstrap\Core\Bootstrap::getConfigVar('form.horizontal.label', 'col-lg-3'); ?>` for the label column and `<?php echo Netzmacht\Bootstrap\Core\Bootstrap::getConfigVar('form.horizontal.control', 'col-lg-9'); ?>` for the control template. The 2nd param defines the default value if no configuration is found.

Feel free to provide it as well or just include the 1cl templates.

**Comment by squareZ** [comment]
- <br> tag removed
- There is nothing to do for the logout module, as this is just a redirection (correct me if I'm wrong)
- done

**Comment by squareZ** [comment]
Done.

**Comment by dmolineus** [comment]
Great. Thanks for your work. 

Gonna make small changes and then merge it so the next release will provide your templates.

**Comment by dmolineus** [comment]
I merged your pull request to a new branch and make some changes. 

- I like you idea to use a default submit button class. So I introduced a new config var for that (So that no one is confused than changing the one for the upload button)
- I added `has-error` class to the error message.
- I use the `alert` component on the logout template.
- I think a 2cl layout is useless on the logout template, so I make it 1 column.
- Fixed the autoload template settings.

https://github.com/contao-bootstrap/templates/commits/feature-login-templates

Please have and look and confirm if you're happy with my changes.

**Comment by squareZ** [comment]
> Please have and look and confirm if you're happy with my changes.

Yes sure and thanks for the pointer (again)! :+1:

**Comment by dmolineus** [comment]
Nice, I've merge the feature branch into develop. So I close this pull request. Merged with 06b495d4e2cf6d187896b449528398e6364e564b

**Pull request closed without merging**
